server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    #表示自己就是注册中心
    fetch-registry: false
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #与eureka的交互地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
